version: "3.8"

services:
  frontend:
    image: frontend
    container_name: frontend
    hostname: frontend
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

  backend:
    image: backend
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"

  