[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "malware_analysis"
version = "0.0.1"
description = "A malware analysis backend"
authors = [
    {name = "Nightlyside"},
    {name = "Arblade"},
]
dependencies = [
    "requests",
    "fastapi",
    "uvicorn",
]

[project.scripts]
serve_malware_analysis = "malware_analysis:main"